"""empty message

Revision ID: 38133dd25b1d
Revises: cb973124dfe3
Create Date: 2022-11-07 16:01:51.731034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38133dd25b1d'
down_revision = 'cb973124dfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('is_saudi', sa.Boolean(), nullable=True),
    sa.Column('is_turkey', sa.Boolean(), nullable=True),
    sa.Column('is_india', sa.Boolean(), nullable=True),
    sa.Column('is_malaysia', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('is_egypt', sa.Boolean(), nullable=True),
    sa.Column('is_georgia', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('job_grade', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('forgot_password_code', sa.String(length=255), nullable=True),
    sa.Column('auth_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(length=1000), nullable=True),
    sa.Column('session_token', sa.String(length=1000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('account_type', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('countries', sa.Column('arabic_currency', sa.String(length=50), nullable=True))
    op.add_column('countries', sa.Column('free_trail_days', sa.String(length=50), nullable=True))
    op.add_column('countries', sa.Column('country_code_2d', sa.String(length=50), nullable=True))
    op.drop_column('countries', 'test')
    op.drop_column('countries', 'test_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('test_mode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('test', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('countries', 'country_code_2d')
    op.drop_column('countries', 'free_trail_days')
    op.drop_column('countries', 'arabic_currency')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
