"""empty message

Revision ID: c12e30db75f0
Revises: a1d64979b662
Create Date: 2022-07-19 22:14:44.539115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12e30db75f0'
down_revision = 'a1d64979b662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=50), nullable=True),
    sa.Column('country_name', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('monthly_amount', sa.String(length=50), nullable=True),
    sa.Column('annually_amount', sa.String(length=50), nullable=True),
    sa.Column('payment_name', sa.String(length=200), nullable=True),
    sa.Column('payment_merchant_id', sa.String(length=50), nullable=True),
    sa.Column('payment_currency', sa.String(length=50), nullable=True),
    sa.Column('payment_request_api_url', sa.String(length=200), nullable=True),
    sa.Column('payment_api_key', sa.String(length=200), nullable=True),
    sa.Column('payment_query_link', sa.String(length=200), nullable=True),
    sa.Column('google_script', sa.String(length=500), nullable=True),
    sa.Column('payment_getway', sa.String(length=200), nullable=True),
    sa.Column('usd_convert', sa.String(length=50), nullable=True),
    sa.Column('payment_with_usd', sa.Boolean(), nullable=True),
    sa.Column('global_currency_name', sa.String(length=50), nullable=True),
    sa.Column('test', sa.String(length=50), nullable=True),
    sa.Column('test_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('country_code_id', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('country_code_id_test', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('payment_getway', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('razorpay_payment_id', sa.String(length=200), nullable=True))
    op.add_column('order', sa.Column('razorpay_order_id', sa.String(length=200), nullable=True))
    op.add_column('order', sa.Column('razorpay_signature', sa.String(length=200), nullable=True))
    op.add_column('order', sa.Column('account_type', sa.String(length=100), nullable=True))
    op.add_column('packages', sa.Column('country_code', sa.String(length=255), nullable=True))
    op.add_column('subscription', sa.Column('db_status', sa.String(length=100), nullable=True))
    op.add_column('subscription', sa.Column('country_code_id', sa.String(length=100), nullable=True))
    op.add_column('subscription', sa.Column('payment_getway', sa.String(length=100), nullable=True))
    op.add_column('subscription', sa.Column('account_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'account_type')
    op.drop_column('subscription', 'payment_getway')
    op.drop_column('subscription', 'country_code_id')
    op.drop_column('subscription', 'db_status')
    op.drop_column('packages', 'country_code')
    op.drop_column('order', 'account_type')
    op.drop_column('order', 'razorpay_signature')
    op.drop_column('order', 'razorpay_order_id')
    op.drop_column('order', 'razorpay_payment_id')
    op.drop_column('order', 'payment_getway')
    op.drop_column('order', 'country_code_id_test')
    op.drop_column('order', 'country_code_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
