"""empty message

Revision ID: 9272976a0386
Revises: e7358002e584
Create Date: 2022-08-11 22:17:06.597703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9272976a0386'
down_revision = 'e7358002e584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('turkish_merchant_id', sa.String(length=200), nullable=True))
    op.add_column('countries', sa.Column('turkish_merchant_key', sa.String(length=200), nullable=True))
    op.add_column('order', sa.Column('turkish_hash_number', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'turkish_hash_number')
    op.drop_column('countries', 'turkish_merchant_key')
    op.drop_column('countries', 'turkish_merchant_id')
    # ### end Alembic commands ###
