"""empty message

Revision ID: d38e4831efe9
Revises: a56444ce83ed
Create Date: 2024-01-18 13:32:32.029532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38e4831efe9'
down_revision = 'a56444ce83ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('delete_account_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'delete_account_at')
    # ### end Alembic commands ###
