"""empty message

Revision ID: 02f71473c34a
Revises: 38133dd25b1d
Create Date: 2023-01-09 04:51:47.215435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f71473c34a'
down_revision = '38133dd25b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_cash', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_cash')
    # ### end Alembic commands ###
