"""empty message

Revision ID: 1a989148c7fa
Revises: 9272976a0386
Create Date: 2022-09-21 05:51:37.017052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a989148c7fa'
down_revision = '9272976a0386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'notes')
    # ### end Alembic commands ###
