"""empty message

Revision ID: 40de08180637
Revises: 5dd1c535dbcf
Create Date: 2022-02-22 13:18:14.599793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40de08180637'
down_revision = '5dd1c535dbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('sub_type_toUpdate', sa.String(length=50), nullable=True))
    op.add_column('order', sa.Column('pos_no_toUpdate', sa.String(length=30), nullable=True))
    op.add_column('order', sa.Column('price_toUpdate', sa.String(length=30), nullable=True))
    op.add_column('subscription', sa.Column('plan_type', sa.String(length=255), nullable=True))
    op.add_column('subscription', sa.Column('price', sa.String(length=255), nullable=True))
    op.add_column('subscription', sa.Column('subscription_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'subscription_status')
    op.drop_column('subscription', 'price')
    op.drop_column('subscription', 'plan_type')
    op.drop_column('order', 'price_toUpdate')
    op.drop_column('order', 'pos_no_toUpdate')
    op.drop_column('order', 'sub_type_toUpdate')
    # ### end Alembic commands ###
