"""empty message

Revision ID: a1d64979b662
Revises: 40de08180637
Create Date: 2022-04-07 14:39:02.641074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d64979b662'
down_revision = '40de08180637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('pos_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'pos_no')
    # ### end Alembic commands ###
