"""empty message

Revision ID: cb973124dfe3
Revises: 1a989148c7fa
Create Date: 2022-10-31 07:02:57.910140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb973124dfe3'
down_revision = '1a989148c7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('subscription', sa.Column('test', sa.String(length=100), nullable=True))
    op.alter_column('subscription', 'business_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'subscription', ['business_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='unique')
    op.alter_column('subscription', 'business_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('subscription', 'test')
    op.drop_column('subscription', 'is_active')
    # ### end Alembic commands ###
