"""empty message

Revision ID: f352e0865dcc
Revises: 02f71473c34a
Create Date: 2023-04-03 22:12:15.487013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f352e0865dcc'
down_revision = '02f71473c34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('test', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'test')
    # ### end Alembic commands ###
