"""empty message

Revision ID: 5dd1c535dbcf
Revises: 
Create Date: 2022-01-30 14:40:28.973835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd1c535dbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('msg_type', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
