"""empty message

Revision ID: a56444ce83ed
Revises: adf686bc3364
Create Date: 2024-01-18 13:31:25.967021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a56444ce83ed'
down_revision = 'adf686bc3364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'delete_account_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('delete_account_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
