"""empty message

Revision ID: adf686bc3364
Revises: d63c64aaac65
Create Date: 2024-01-18 12:43:04.770965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf686bc3364'
down_revision = 'd63c64aaac65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('delete_account_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'delete_account_at')
    # ### end Alembic commands ###
