"""empty message

Revision ID: e7358002e584
Revises: c12e30db75f0
Create Date: 2022-07-19 22:23:36.110090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7358002e584'
down_revision = 'c12e30db75f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('pos_no_code', sa.String(length=255), nullable=True),
    sa.Column('pos_no', sa.Integer(), nullable=True),
    sa.Column('pos_string_en', sa.String(length=255), nullable=True),
    sa.Column('pos_string_ar', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('currency_en', sa.String(length=255), nullable=True),
    sa.Column('currency_ar', sa.String(length=255), nullable=True),
    sa.Column('code_hash', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    # ### end Alembic commands ###
